### ISSUE TITLE
Throwing Error on rebuilding

### ISSUE THREAD

**Issue by kandhavivekraj** [ef4/prember#21]
While changing something in files and getting following error rebuilding

`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::7784
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (/Users/kandha-5225/ember-source-code/prember/node_modules/express/lib/application.js:618:24)
    at Prerender.build (/Users/****/ember-source-code/prember/lib/prerender.js:89:8)
    at <anonymous>
`

I suspect, this is occurred due to [this](https://github.com/ef4/prember/blob/master/lib/prerender.js#L89) line. Express creates a new server instance on using `app.listen( )`.

**Comment by willviles** [comment]
I came across this, however soon realised I hadn't followed the [README](https://github.com/ef4/prember#using-prember-in-development) correctly. This will sort it out:

```bash
$ ember install prember-middleware
```

**Comment by ef4** [comment]
I think the root bug here is that we aren't cleanly shutting down the express server at the end of a build.
